services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/database:/directus/database
    environment:
      KEY: '255d861b-5ea1-5996-9c3b-102b23f5fc85'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/data.db'
      
      ADMIN_EMAIL: 'admin@cincinhotels.com'
      ADMIN_PASSWORD: 'admin123'
      
      # Basic configuration
      CORS_ENABLED: 'true'
      CORS_ORIGIN: '*'
      PUBLIC_URL: 'http://localhost:8055'
