version: '3'
services:
  directus:
    image: directus/directus:latest
    restart: always
    ports:
      - 8055:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/database:/directus/database
      - ./directus/extensions:/directus/extensions
    environment:
      KEY: '${DIRECTUS_KEY}'
      SECRET: '${DIRECTUS_SECRET}'
      
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/data.db'
      
      ADMIN_EMAIL: '${DIRECTUS_ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${DIRECTUS_ADMIN_PASSWORD}'
      
      # CORS settings for production
      CORS_ENABLED: 'true'
      CORS_ORIGIN: '${NEXT_PUBLIC_SITE_URL}'
      
      # Public URL
      PUBLIC_URL: '${NEXT_PUBLIC_DIRECTUS_URL}'
      
      # Cache settings
      CACHE_ENABLED: 'true'
      CACHE_TTL: '30'
      CACHE_CONTROL_S_MAXAGE: '3600'
      CACHE_AUTO_PURGE: 'true'
      
      # Storage settings
      STORAGE_LOCATIONS: 'local'
      STORAGE_LOCAL_DRIVER: 'local'
      STORAGE_LOCAL_ROOT: '/directus/uploads'
      
      # File optimizations
      ASSETS_TRANSFORM_MAX_CONCURRENT: '10'
      ASSETS_CACHE_TTL: '86400'
      
      # Security settings
      RATE_LIMITER_ENABLED: 'true'
      RATE_LIMITER_POINTS: '50'
      RATE_LIMITER_DURATION: '1'
      RATE_LIMITER_STORE: 'memory'
      
      # Logging
      LOG_LEVEL: 'info'
      LOG_STYLE: 'json'
    networks:
      - directus-net

networks:
  directus-net:
    driver: bridge
EOF < /dev/null