version: '3'
services:
  database:
    container_name: cincinhotels_db
    image: postgres:14-alpine
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  cache:
    container_name: cincinhotels_cache
    image: redis:6-alpine
    networks:
      - directus
    volumes:
      - ./data/cache:/data

  directus:
    container_name: cincinhotels_directus
    image: directus/directus:latest
    ports:
      - ${PORT}:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - database
      - cache
    environment:
      KEY: ${KEY}
      SECRET: ${SECRET}
      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CORS_ENABLED: 'true'
      CORS_ORIGIN: ${CORS_ORIGIN}
      PUBLIC_URL: ${PUBLIC_URL}
      RATE_LIMITER_ENABLED: 'true'
      RATE_LIMITER_STORE: 'redis'
      RATE_LIMITER_REDIS: 'redis://cache:6379'
      RATE_LIMITER_POINTS: 50
      RATE_LIMITER_DURATION: 1
      CONTENT_SECURITY_POLICY_DIRECTIVES__IMG_SRC: ${PUBLIC_URL} 'self' *.unsplash.com data:
      STORAGE_LOCATIONS: 'local'
      STORAGE_LOCAL_PUBLIC_URL: ${PUBLIC_URL}/uploads
      EMAIL_TRANSPORT: 'sendmail'
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_SENDMAIL_NEW_LINE: 'unix'
      EMAIL_SENDMAIL_PATH: '/usr/sbin/sendmail'

networks:
  directus:
    name: directus_network